### PR TITLE
Adding new github actions

### PR DESCRIPTION
**Pull request by JDGiardino**
Adding the following Github actions : 
**Lint** (documentation here https://github.com/marketplace/actions/lint-action)

- Shows linting errors on GitHub commits and PRs
- Allows auto-fixing issues 

**First Interaction** (documentation here https://github.com/marketplace/actions/first-interaction)
- An action for filtering pull requests and issues from first-time contributors.

### CODE REVIEW

**Comment by JDGiardino** [comment]
This is what it looks like when I trial & error lol ☝️

**Comment by JDGiardino** [comment]
Let me summarize my troubleshooting from above : 

I am trying to use a Github action as a Linter (https://github.com/marketplace/actions/lint-action).  The problem was it was erroring on parsing my file gunicorn_config.py because it's not a normal Python file (but required for my Digital Ocean deployment).  So I wanted to ignore this file when the linter runs.  The problem is, the Github Action version for Black linter does not seem to have any "--exclude" option.  

From here I decided instead of using the Github action from that link above, that instead I would just use the actual Black command in the Github Workflow file `poetry run black . --exclude gunicorn_config.py`.  The problem here ended up being that this actually goes ahead and forces the actual changes rather than the Github action that just provides a warning.

**Comment by JDGiardino** [comment]
Okay so I did find that black has a --check flag that doesn't auto force the formatting changes.  But it only shows the file it would change and not the actual change it would make.  Where was the linter Github Action showed you the exact line in the code diff

**Comment by JDGiardino** [comment]
Okay fine so there was a -diff flag for black and that appears to be working the way I want.  I guess I just thought using the linter Github Action was cool but maybe it's better not to rely on someone else's action and just rely on the basic black commands.

**Review by AleksandrGorbach — APPROVED** [review]

**Pull request merged**
